// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcphwomrriernqsvyllp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjcGh3b21ycmllcm5xc3Z5bGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODIzMjYsImV4cCI6MjA1Nzk1ODMyNn0.80Y6cVIXd-IvPOpbn-GciqyYHUKlT3xD4CbnGZ294Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);